<div class="flex text-[{{ $size }}] gap-2">
    @if ($ratingAvg == 5)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
    @elseif($ratingAvg >= 4.5)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star-half text-[#866f57]"></i>
    @elseif($ratingAvg >= 4)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
    @elseif($ratingAvg >= 3.5)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star-half text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
    @elseif($ratingAvg >= 3)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
    @elseif($ratingAvg >= 2.5)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star-half text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
    @elseif($ratingAvg >= 2)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
    @elseif($ratingAvg >= 1.5)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-fill ph-star-half text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
    @elseif($ratingAvg >= 1)
        <i class="ph-fill ph-star text-[#866f57]"></i>
        <i class="ph-bold ph-star text-[#866f57]"></i>
        <i class="ph-bold ph-star text-[#866f57]"></i>
        <i class="ph-bold ph-star text-[#866f57]"></i>
        <i class="ph-bold ph-star text-[#866f57]"></i>
    @elseif($ratingAvg >= 0.5)
        <i class="ph-fill ph-star-half text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
    @else
        <i class="ph-fill ph-star-half text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
        <i class="ph ph-star text-[#866f57]"></i>
    @endif
</div>
